POST http://localhost:8080/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="photo_2022-04-25_15-21-43.jpg"

< C:\Users\photo_2022-04-25_15-21-43.jpg
--WebAppBoundary--

###
GET http://localhost:8080/attach/open_general/7c3e3ba5-cfd8-4cae-b396-802bd41329cf

###
GET http://localhost:8080/attach/download/7c3e3ba5-cfd8-4cae-b396-802bd41329cf

###
DELETE http://localhost:8080/attach/adm/delete/7c3e3ba5-cfd8-4cae-b396-802bd41329cf
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3IiwiaWF0IjoxNjUzMTE5MDE4LCJleHAiOjE2NTM0NzkwMTgsImlzcyI6Im1hemdpIHByb2R1Y3Rpb24iLCJyb2xlIjoiQURNSU4ifQ.jxsv84tbvanJsz1Y5f9Ib9vjYikTWf0fnecvkWG7jX0